### ISSUE TITLE
Problem On Phone

### ISSUE THREAD

**Issue by hieuhiti** [fletcherrippon/JavaScriptQRCodeReader#1]
Thanks Fletcher Rippon about JavaScriptQRCodeReader.

I tested it on a computer browser, it's great.
But, on Phone:
+ IOS: It not working at all Browser
+ Android: Working on Chrome, but It scan with Front Camera, How to use back camera?
Please help me, Thanks you!

**Comment by ronninaldo** [comment]
Supported Browsers:
https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector

To use back camera set constraints in main.js (in 'Check for a camera', before 'Start video stream') to
```
// Check for a camera
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) { 
const constraints = {
     video: { facingMode: { exact: "environment" } },
    audio: false
  };
...
```
(see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)

**Comment by hieuhiti** [comment]
> Supported Browsers:
> https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector
> 
> To use back camera set constraints in main.js (in 'Check for a camera', before 'Start video stream') to
> 
> ```
> // Check for a camera
> if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) { 
> const constraints = {
>      video: { facingMode: { exact: "environment" } },
>     audio: false
>   };
> ...
> ```
> 
> (see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)

Thanks for your explanation. I found the solution with ZXing libraries.

**Comment by fletcherrippon** [comment]
@hieuhiti thanks for the support and finding this issue I will definitely take a look at browser compatibility next this code was written for one of my articles currently working on the second half of it.

In the first part of the article it goes very in-depth with everything about the barcode scanner API but currently has no solutions for becoming compatible with other browsers (will be working on a solution for you soon) here is the link if you would like to take a look at what I have written about it  https://link.medium.com/05SL45aQdjb

**Comment by hieuhiti** [comment]
@fletcherrippon  You can refer https://github.com/mebjas/html5-qrcode, the solution with ZXing libraries. It's works quite well on mobile environment and most browsers.
